# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kitai',
                'doc_host': 'https://taya-nicholas.github.io',
                'git_url': 'https://github.com/taya-nicholas/kitai',
                'lib_path': 'kitai'},
  'syms': {'kitai.core': {'kitai.core.foo': ('core.html#foo', 'kitai/core.py')}}}
